/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tcs.tallerListas;

import com.tcs.tallerListas.beans.Estudiante;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;


public class IngresoEstudiantes {

	static ArrayList<Estudiante> estudiantes = new ArrayList<>();
	static Scanner in = new Scanner(System.in);
	static String opcMenu;

	public static void main(String[] args) {

		estudiantes = lecturaArchivo();

		System.out.println();
		String menu =   "\n"+
				        "################ Ingreso de estudiantes ################\n" +
						"         * 1 Consultar número estudiante.\n" +
						"         * 2 Consultar estudiante entre los 6 y 10 años de edad.\n" +
						"         * 3 Consultar listado de grado.\n" +
						"         * 4 Consultar identificación de los estudiante que empieza con TI\n" +
						"         * 5 Consultar estudiantes repitentes\n" +
						"         * 0 Salir de la aplicacion\n";


		//Uso clico do while() para iniciar menu
		@Deprecated(since = "1.2", forRemoval = true)
		Integer opMenu = new Integer(0);

		do {
			System.out.println(menu);
			opMenu = in.nextInt();
			switch (opMenu.toString()) {
				case "1":
					opcMenu = in.nextLine();
					int a = estudiantes.size();
					System.out.println("El número de estudiantes es: " + a);
					break;
				case "2":
					opcMenu = in.nextLine();
					int b = edadEntreRango();
					System.out.println("Número de estudiantes entre 8 a 10 años de edad: " + b);
					break;
				case "3":
					opcMenu = in.nextLine();
					System.out.println("\n################ Listado de los grados ################");
					listadoGrado();
					break;
				case "4":
					opcMenu = in.nextLine();
					System.out.println("\n################ Identificación con TI ################");
					busquedadId();
					break;
				case "5":
					opcMenu = in.nextLine();
					consultarRepitentes();
					break;
				case "0":
					System.out.println("Muchas gracias por usar nuestra app, hasta luego");
					break;
				default:
					System.out.println("El valor ingresado no es una opcion de menu");
					break;
			}
		} while (!opMenu.toString().equals("0"));
		in.close();
	}

	public static ArrayList lecturaArchivo(){
		ArrayList listaEstudiantes = new ArrayList<>();
		try {
			Scanner data = new Scanner(new File("src/main/resources/data.txt"));

			while (data.hasNextLine()) {
				//String[] estData = data.nextLine().split(",");
				Scanner estData = new Scanner(data.nextLine());
				estData.useDelimiter(",");
				Estudiante e = new Estudiante();
				e.setId(estData.next());
				e.setNombre(estData.next());
				e.setEdad(estData.nextInt());
				e.setEstado(estData.next());
				e.setGrado(estData.next());

				listaEstudiantes.add(e);
			}
			data.close();
		} catch (FileNotFoundException ex) {
			System.err.println("No se logro abrir el archivo.");
		} catch (NumberFormatException ex) {
			System.err.println("Se han introducido caracteres no numéricos");
		}
		finally {
			System.err.println("Todo se encuentra listo.");
		}
		return listaEstudiantes;
	}

	public static Integer edadEntreRango() {
		int b = 0;
		for (Estudiante estudiante : estudiantes) {
			if ( estudiante.getEdad() >= 6  && estudiante.getEdad() <= 10){
				b++;
			}
		}
		return b;
	}

	public static void busquedadId(){
		ArrayList idEmpiezaTI = new ArrayList<>();

		for (Estudiante estudiante : estudiantes) {
			if (estudiante.getId().substring(0,2).equals("TI")){
				idEmpiezaTI.add("Edad: " + estudiante.getEdad() + ", Grado:" + estudiante.getGrado());
			}
		}

		for(int i = 0; i < idEmpiezaTI.size(); i++)  {
			System.out.println(idEmpiezaTI.get(i));
		}

	}

	public static void listadoGrado(){
		ArrayList<String> listaJardin  = new ArrayList<>();
		ArrayList<String> listaPrimero = new ArrayList<>();
		ArrayList<String> listaSegundo = new ArrayList<>();
		ArrayList<String> listaTercero = new ArrayList<>();
		ArrayList<String> listaCuarto  = new ArrayList<>();
		ArrayList<String> listaQuinto  = new ArrayList<>();

		for (Estudiante estudiante : estudiantes) {
			if (estudiante.getGrado().equals("Jardin")){
				listaJardin.add(estudiante.getId() + "," + estudiante.getNombre() + "," + estudiante.getEdad()+ ","
						+ estudiante.getGrado());
			}
		}

		System.out.println("Listado de jardin:");
		for(int i = 0; i < listaJardin.size(); i++)  {
			System.out.println(listaJardin.get(i));
		}

		for (Estudiante estudiante : estudiantes) {
			if (estudiante.getGrado().equals("Primero")){
				listaPrimero.add(estudiante.getId() + "," + estudiante.getNombre() + "," + estudiante.getEdad()+ ","
						+ estudiante.getGrado());
			}
		}

		System.out.println("\nListado de primero:");
		for(int i = 0; i < listaPrimero.size(); i++)  {
			System.out.println(listaPrimero.get(i));
		}

		for (Estudiante estudiante : estudiantes) {
			if (estudiante.getGrado().equals("Segundo")){
				listaSegundo.add(estudiante.getId() + "," + estudiante.getNombre() + "," + estudiante.getEdad()+ ","
						+ estudiante.getGrado());
			}
		}

		System.out.println("\nListado de segundo:");
		for(int i = 0; i < listaSegundo.size(); i++)  {
			System.out.println(listaSegundo.get(i));
		}

		for (Estudiante estudiante : estudiantes) {
			if (estudiante.getGrado().equals("Tercero")){
				listaTercero.add(estudiante.getId() + "," + estudiante.getNombre() + "," + estudiante.getEdad()+ ","
						+ estudiante.getGrado());
			}
		}

		System.out.println("\nListado de Tercero:");
		for(int i = 0; i < listaTercero.size(); i++)  {
			System.out.println(listaTercero.get(i));
		}

		for (Estudiante estudiante : estudiantes) {
			if (estudiante.getGrado().equals("Cuarto")){
				listaCuarto.add(estudiante.getId() + "," + estudiante.getNombre() + "," + estudiante.getEdad()+ ","
						+ estudiante.getGrado());
			}
		}

		System.out.println("\nListado de Cuarto:");
		for(int i = 0; i < listaCuarto.size(); i++)  {
			System.out.println(listaCuarto.get(i));
		}

		for (Estudiante estudiante : estudiantes) {
			if (estudiante.getGrado().equals("Quinto")){
				listaQuinto.add(estudiante.getId() + "," + estudiante.getNombre() + "," + estudiante.getEdad()+ ","
						+ estudiante.getGrado());
			}
		}

		System.out.println("\nListado de Quinto:");
		for(int i = 0; i < listaQuinto.size(); i++)  {
			System.out.println(listaQuinto.get(i));
		}
	}

	public static void consultarRepitentes(){
		ArrayList<String> estRepitente  = new ArrayList<>();

		for (Estudiante estudiante : estudiantes) {
			if (estudiante.getEstado().equals("Rechazado")){
				estRepitente.add(estudiante.getNombre());
			}
		}

		System.out.println("\nListado de Estudiantes Repitentes:");
		for(int i = 0; i < estRepitente.size(); i++)  {
			System.out.println(estRepitente.get(i));
		}
	}
	
}
